//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.04 at 04:43:49 PM GMT-08:00 
//

@javax.xml.bind.annotation.XmlSchema(elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@XmlJavaTypeAdapter(value=StringTrimAdapter.class,type=String.class)
package org.zstack.core.errorcode.schema;

import org.zstack.utils.jaxb.StringTrimAdapter;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;