package org.zstack.core.timeout;

import org.zstack.core.GlobalProperty;
import org.zstack.core.GlobalPropertyDefinition;

/**
 * Created by xing5 on 2016/3/26.
 */
@GlobalPropertyDefinition
public class ApiTimeoutGlobalProperty {
    @GlobalProperty(name="ApiTimeout.org.zstack.header.image.APIAddImageMsg", defaultValue = "org.zstack.header.storage.backup.DownloadImageMsg, org.zstack.storage.backup.sftp.SftpBackupStorageCommands$DownloadCmd, org.zstack.storage.ceph.backup.CephBackupStorageBase$DownloadCmd,org.zstack.storage.primary.smp.KvmBackend$SftpDownloadBitsCmd, org.zstack.storage.fusionstor.backup.FusionstorBackupStorageBase$DownloadCmd; 3h")
    public static String APIAddImageMsg;
    @GlobalProperty(name="ApiTimeout.org.zstack.header.image.APICreateRootVolumeTemplateFromRootVolumeMsg", defaultValue = "org.zstack.header.storage.backup.AllocateBackupStorageMsg, org.zstack.header.vm.CreateTemplateFromVmRootVolumeMsg, org.zstack.storage.ceph.primary.CephPrimaryStorageBase$CpCmd, org.zstack.storage.ceph.primary.CephPrimaryStorageBase$SftpUpLoadCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$CreateTemplateFromVolumeCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$DeleteBitsCmd, org.zstack.storage.primary.local.LocalStorageKvmSftpBackupStorageMediatorImpl$SftpUploadBitsCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$CreateTemplateFromVolumeCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$UploadToSftpCmd,org.zstack.storage.primary.smp.KvmBackend$CreateTemplateFromVolumeCmd,org.zstack.storage.primary.smp.KvmBackend$SftpUploadBitsCmd, org.zstack.storage.fusionstor.primary.FusionstorPrimaryStorageBase$CpCmd, org.zstack.storage.fusionstor.primary.FusionstorPrimaryStorageBase$SftpUpLoadCmd; 3h")
    public static String APICreateRootVolumeTemplateFromRootVolumeMsg;
    @GlobalProperty(name="ApiTimeout.org.zstack.header.image.APICreateDataVolumeTemplateFromVolumeMsg", defaultValue = "org.zstack.header.volume.CreateDataVolumeTemplateFromDataVolumeMsg, org.zstack.header.storage.primary.CreateTemplateFromVolumeOnPrimaryStorageMsg, org.zstack.storage.ceph.primary.CephPrimaryStorageBase$CpCmd, org.zstack.storage.ceph.primary.CephPrimaryStorageBase$SftpUpLoadCmd, org.zstack.storage.primary.iscsi.IscsiFileSystemBackendPrimaryStorageCommands$UploadToSftpCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$CreateTemplateFromVolumeCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$DeleteBitsCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$CreateTemplateFromVolumeCmd,org.zstack.storage.primary.smp.KvmBackend$CreateTemplateFromVolumeCmd, org.zstack.storage.fusionstor.primary.FusionstorPrimaryStorageBase$CpCmd, org.zstack.storage.fusionstor.primary.FusionstorPrimaryStorageBase$SftpUpLoadCmd; 3h")
    public static String APICreateDataVolumeTemplateFromVolumeMsg;
    @GlobalProperty(name="ApiTimeout.org.zstack.header.volume.APICreateDataVolumeFromVolumeSnapshotMsg", defaultValue = "org.zstack.header.storage.snapshot.CreateDataVolumeFromVolumeSnapshotMsg, org.zstack.header.storage.primary.CreateVolumeFromVolumeSnapshotOnPrimaryStorageMsg, org.zstack.storage.ceph.primary.CephPrimaryStorageBase$CpCmd, org.zstack.storage.primary.iscsi.IscsiFileSystemBackendPrimaryStorageCommands$DownloadBitsFromSftpBackupStorageCmd, org.zstack.storage.primary.local.LocalStorageKvmSftpBackupStorageMediatorImpl$SftpDownloadBitsCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$MergeSnapshotCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$DownloadBitsFromSftpBackupStorageCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$RebaseAndMergeSnapshotsCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$DeleteCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$MoveBitsCmd, org.zstack.header.storage.primary.DeleteBitsOnPrimaryStorageMsg, org.zstack.storage.primary.local.LocalStorageKvmBackend$DeleteBitsCmd, org.zstack.storage.primary.smp.KvmBackend$MergeSnapshotCmd,org.zstack.storage.primary.smp.KvmBackend$OfflineMergeSnapshotCmd, org.zstack.storage.fusionstor.primary.FusionstorPrimaryStorageBase$CpCmd; 3h")
    public static String APICreateDataVolumeFromVolumeSnapshotMsg;
    @GlobalProperty(name="ApiTimeout.org.zstack.storage.primary.local.APILocalStorageMigrateVolumeMsg", defaultValue = "org.zstack.storage.primary.local.LocalStorageKvmBackend$DeleteBitsCmd, org.zstack.storage.primary.local.LocalStorageKvmSftpBackupStorageMediatorImpl$SftpDownloadBitsCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$GetBackingFileCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$GetMd5Cmd, org.zstack.storage.primary.local.LocalStorageKvmMigrateVmFlow$CopyBitsFromRemoteCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$DeleteBitsCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$CheckMd5sumCmd; 3h")
    public static String APILocalStorageMigrateVolumeMsg;
    @GlobalProperty(name="ApiTimeout.org.zstack.header.image.APICreateRootVolumeTemplateFromVolumeSnapshotMsg", defaultValue = "org.zstack.header.storage.snapshot.CreateTemplateFromVolumeSnapshotMsg, org.zstack.header.storage.primary.CreateTemplateFromVolumeSnapshotOnPrimaryStorageMsg, org.zstack.storage.ceph.primary.CephPrimaryStorageBase$CpCmd, org.zstack.storage.primary.local.LocalStorageKvmSftpBackupStorageMediatorImpl$SftpDownloadBitsCmd, org.zstack.storage.primary.local.LocalStorageKvmBackend$RebaseAndMergeSnapshotsCmd, org.zstack.storage.primary.local.LocalStorageKvmSftpBackupStorageMediatorImpl$SftpUploadBitsCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$MergeSnapshotCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$DownloadBitsFromSftpBackupStorageCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$RebaseAndMergeSnapshotsCmd, org.zstack.storage.primary.nfs.NfsPrimaryStorageKVMBackendCommands$MoveBitsCmd, org.zstack.storage.primary.smp.KvmBackend$MergeSnapshotCmd,org.zstack.storage.primary.smp.KvmBackend$OfflineMergeSnapshotCmd, org.zstack.storage.fusionstor.primary.FusionstorPrimaryStorageBase$CpCmd; 3h")
    public static String APICreateRootVolumeTemplateFromVolumeSnapshotMsg;
    @GlobalProperty(name="ApiTimeout.org.zstack.header.volume.APICreateVolumeSnapshotMsg", defaultValue = "org.zstack.header.storage.snapshot.CreateVolumeSnapshotMsg,org.zstack.header.storage.primary.TakeSnapshotMsg,org.zstack.header.host.TakeSnapshotOnHypervisorMsg,org.zstack.storage.ceph.primary.CephPrimaryStorageBase$CreateSnapshotCmd,org.zstack.storage.fusionstor.primary.FusionstorPrimaryStorageBase$CreateSnapshotCmd,org.zstack.kvm.KVMAgentCommands$TakeSnapshotCmd; 3h")
    public static String APICreateVolumeSnapshotMsg;
}
