package org.zstack.header.server.flow;

/**
 * Shared {@code Map data} keys for the Path-2 FlowChain composed of
 * {@code AutoAssociateFlow → CreatePhysicalServerRoleFlow → InitPhysicalServerCapacityFlow}.
 *
 * <p>Path 2 = legacy {@code AddKVMHostMsg} / {@code AddBareMetal2ChassisMsg} flow. KVM and
 * BM2 modules populate these keys before invoking the chain, then read {@link #SERVER_UUID}
 * and {@link #ROLE_UUID} back after the chain commits.</p>
 *
 * <p>Path 3 = Container {@code processNodeTransactional} uses a single {@code @Transactional}
 * method (not a FlowChain) and references these keys only for documentation parity.</p>
 *
 * <p>Phase 3 fix-plan U1-lead.</p>
 */
public final class PathTwoFlowDataKey {
    private PathTwoFlowDataKey() {}

    // ---- input keys (caller fills before invoking the chain) ----

    /** Pre-supplied PS UUID (when {@code AddKVMHostMsg.serverUuid} is non-null), or {@code null}
     *  to trigger {@code AutoAssociateFlow}'s three-tier fallback. */
    public static final String SERVER_UUID = "PhysicalServer.flow.serverUuid";

    /** {@link org.zstack.header.server.RoleMatchContext} (serialNumber / oobAddress /
     *  managementIp / zoneUuid) for AutoAssociate. Required when {@link #SERVER_UUID} is null. */
    public static final String MATCH_CONTEXT = "PhysicalServer.flow.matchContext";

    /** Cluster UUID — used by AutoAssociate to resolve the bound ServerPool. */
    public static final String CLUSTER_UUID = "PhysicalServer.flow.clusterUuid";

    /** Role UUID == role-side entity UUID
     *  ({@code HostVO.uuid} for KVM, {@code BareMetal2ChassisVO.uuid} for BM2).
     *  Pre-generated by caller per ADR-012. */
    public static final String ROLE_UUID = "PhysicalServer.flow.roleUuid";

    /** {@link org.zstack.header.server.ServerRoleType} string value
     *  (KVM_HOST / BAREMETAL2 / CONTAINER). */
    public static final String ROLE_TYPE = "PhysicalServer.flow.roleType";

    /** {@link org.zstack.header.server.SchedulingMode} value. */
    public static final String SCHEDULING_MODE = "PhysicalServer.flow.schedulingMode";

    // ---- internal bookkeeping (Flows fill — do not read externally) ----

    /** True when {@code CreatePhysicalServerRoleFlow} found an existing RoleVO and skipped persist. */
    public static final String ROLE_PRE_EXISTED = "PhysicalServer.flow.rolePreExisted";

    /** {@code PhysicalServerRoleVO.uuid} persisted by {@code CreatePhysicalServerRoleFlow}
     *  (used by rollback). */
    public static final String ROLE_VO_PK = "PhysicalServer.flow.roleVoPk";

    /** True when {@code InitPhysicalServerCapacityFlow} found an existing capacity row
     *  and skipped persist. */
    public static final String CAPACITY_PRE_EXISTED = "PhysicalServer.flow.capacityPreExisted";
}
