DROP PROCEDURE IF EXISTS AddFkPciDeviceVOVmInstanceEO;
DELIMITER $$
CREATE PROCEDURE AddFkPciDeviceVOVmInstanceEO()
BEGIN
    IF (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'FOREIGN KEY' AND TABLE_NAME = 'PciDeviceVO' AND CONSTRAINT_NAME = 'fkPciDeviceVOVmInstanceEO') = 0 THEN
ALTER TABLE PciDeviceVO
    ADD CONSTRAINT fkPciDeviceVOVmInstanceEO FOREIGN KEY (vmInstanceUuid) REFERENCES VmInstanceEO(uuid) ON DELETE SET NULL;
END IF;
END $$
DELIMITER ;
CALL AddFkPciDeviceVOVmInstanceEO();
