CREATE TABLE IF NOT EXISTS `zstack`.`IAM2CreatorProvenanceVO` (
    `uuid` VARCHAR(32) NOT NULL,
    `resourceUuid` VARCHAR(32) NOT NULL,
    `resourceType` VARCHAR(64) NOT NULL,
    `resourceNameSnapshot` VARCHAR(255) DEFAULT NULL,
    `actorUuid` VARCHAR(32) DEFAULT NULL,
    `actorNameSnapshot` VARCHAR(255) DEFAULT NULL,
    `projectUuid` VARCHAR(32) DEFAULT NULL,
    `projectNameSnapshot` VARCHAR(255) DEFAULT NULL,
    `sourceType` VARCHAR(64) NOT NULL,
    `operationUuid` VARCHAR(64) DEFAULT NULL,
    `requestHash` VARCHAR(128) DEFAULT NULL,
    `createDate` TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:00',
    PRIMARY KEY (`uuid`),
    UNIQUE KEY `ukIAM2CreatorProvenanceVOResource` (`resourceUuid`, `resourceType`),
    KEY `idxIAM2CreatorProvenanceVOActor` (`actorUuid`),
    KEY `idxIAM2CreatorProvenanceVOProject` (`projectUuid`),
    KEY `idxIAM2CreatorProvenanceVOOperation` (`operationUuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `zstack`.`IAM2ProjectAutonomyAuditVO` (
    `uuid` VARCHAR(32) NOT NULL,
    `operationUuid` VARCHAR(64) NOT NULL,
    `apiName` VARCHAR(255) NOT NULL,
    `action` VARCHAR(64) NOT NULL,
    `actorUuid` VARCHAR(32) DEFAULT NULL,
    `actorNameSnapshot` VARCHAR(255) DEFAULT NULL,
    `projectUuid` VARCHAR(32) DEFAULT NULL,
    `projectNameSnapshot` VARCHAR(255) DEFAULT NULL,
    `targetUuid` VARCHAR(32) DEFAULT NULL,
    `targetType` VARCHAR(64) DEFAULT NULL,
    `targetNameSnapshot` VARCHAR(255) DEFAULT NULL,
    `decision` VARCHAR(32) NOT NULL,
    `reasonCode` VARCHAR(128) DEFAULT NULL,
    `sourceType` VARCHAR(64) NOT NULL,
    `requestHash` VARCHAR(128) DEFAULT NULL,
    `managementNodeUuid` VARCHAR(32) DEFAULT NULL,
    `createDate` TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:00',
    PRIMARY KEY (`uuid`),
    UNIQUE KEY `ukIAM2ProjectAutonomyAuditVOOperation` (`operationUuid`),
    KEY `idxIAM2ProjectAutonomyAuditVOActor` (`actorUuid`),
    KEY `idxIAM2ProjectAutonomyAuditVOProject` (`projectUuid`),
    KEY `idxIAM2ProjectAutonomyAuditVOTarget` (`targetUuid`, `targetType`),
    KEY `idxIAM2ProjectAutonomyAuditVOCreateDate` (`createDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
