//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 11:06:40 PM CST 
//


package org.zstack.test.deployer.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageStoreBackupStorageConfig")
public class ImageStoreBackupStorageConfig
        extends BackupStorageConfigBase {

    @XmlAttribute(name = "hostname")
    protected String hostname;
    @XmlAttribute(name = "username")
    protected String username;
    @XmlAttribute(name = "password")
    protected String password;
    @XmlAttribute(name = "sshPort")
    protected String sshPort;

    public String getHostname() {
        if (hostname == null) {
            return "localhost";
        } else {
            return hostname;
        }
    }

    public void setHostname(String value) {
        this.hostname = value;
    }

    public String getUsername() {
        if (username == null) {
            return "root";
        } else {
            return username;
        }
    }

    public void setUsername(String value) {
        this.username = value;
    }

    public String getPassword() {
        if (password == null) {
            return "password";
        } else {
            return password;
        }
    }

    public void setPassword(String value) {
        this.password = value;
    }

    public String getSshPort() {
        if (sshPort == null) {
            return "22";
        } else {
            return this.sshPort;
        }
    }

    public void setSshPort(String sshPort) {
        this.sshPort = sshPort;
    }
}
