//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.29 at 03:47:00 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://zstack.org/schema/zstack", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.zstack.test.deployer.schema;
