//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.23 at 09:54:14 PM GMT-08:00 
//


package org.zstack.test;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.zstack.test package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.zstack.test
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UnitTestSuiteConfig }
     */
    public UnitTestSuiteConfig createUnitTestSuiteConfig() {
        return new UnitTestSuiteConfig();
    }

    /**
     * Create an instance of {@link UnitTestSuiteConfig.TestCase }
     */
    public UnitTestSuiteConfig.TestCase createUnitTestSuiteConfigTestCase() {
        return new UnitTestSuiteConfig.TestCase();
    }

    /**
     * Create an instance of {@link UnitTestSuiteConfig.Import }
     */
    public UnitTestSuiteConfig.Import createUnitTestSuiteConfigImport() {
        return new UnitTestSuiteConfig.Import();
    }

}
