//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.23 at 09:54:14 PM GMT-08:00 
//


package org.zstack.test;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="TestCase">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="timeout" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                   &lt;attribute name="repeatTimes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Import">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="timeout" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "testCase",
        "_import"
})
@XmlRootElement(name = "UnitTestSuiteConfig")
public class UnitTestSuiteConfig {

    @XmlElement(name = "TestCase")
    protected List<UnitTestSuiteConfig.TestCase> testCase;
    @XmlElement(name = "Import")
    protected List<UnitTestSuiteConfig.Import> _import;
    @XmlAttribute(name = "timeout")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer timeout;

    /**
     * Gets the value of the testCase property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCase property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCase().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitTestSuiteConfig.TestCase }
     */
    public List<UnitTestSuiteConfig.TestCase> getTestCase() {
        if (testCase == null) {
            testCase = new ArrayList<UnitTestSuiteConfig.TestCase>();
        }
        return this.testCase;
    }

    /**
     * Gets the value of the import property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the import property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImport().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitTestSuiteConfig.Import }
     */
    public List<UnitTestSuiteConfig.Import> getImport() {
        if (_import == null) {
            _import = new ArrayList<UnitTestSuiteConfig.Import>();
        }
        return this._import;
    }

    /**
     * Gets the value of the timeout property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setTimeout(Integer value) {
        this.timeout = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Import {

        @XmlAttribute(name = "resource", required = true)
        protected String resource;

        /**
         * Gets the value of the resource property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getResource() {
            return resource;
        }

        /**
         * Sets the value of the resource property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setResource(String value) {
            this.resource = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="timeout" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *       &lt;attribute name="repeatTimes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TestCase {

        @XmlAttribute(name = "class", required = true)
        protected String clazz;
        @XmlAttribute(name = "timeout")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer timeout;
        @XmlAttribute(name = "repeatTimes")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer repeatTimes;

        /**
         * Gets the value of the clazz property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the timeout property.
         *
         * @return possible object is
         * {@link Integer }
         */
        public Integer getTimeout() {
            return timeout;
        }

        /**
         * Sets the value of the timeout property.
         *
         * @param value allowed object is
         *              {@link Integer }
         */
        public void setTimeout(Integer value) {
            this.timeout = value;
        }

        /**
         * Gets the value of the repeatTimes property.
         *
         * @return possible object is
         * {@link Integer }
         */
        public Integer getRepeatTimes() {
            return repeatTimes;
        }

        /**
         * Sets the value of the repeatTimes property.
         *
         * @param value allowed object is
         *              {@link Integer }
         */
        public void setRepeatTimes(Integer value) {
            this.repeatTimes = value;
        }

    }

}
