= 网络资源

用户需要通过云平台按需的创建虚拟网络，通过虚拟网络打通云主机之间的链路，云主机和外部网络的链路。为此，ZStack云平台提供了如下类型的网
络资源：

* 二层网络
* 三层网络

== 二层网络
云主机的流量通过虚拟网卡到达物理服务器，二层网络定义服务器如何转发云主机的流量。目前支持的网络类型有:

* VLAN网络
[quote]
====
物理服务器给云主机的流量打上VLAN标签，然后经过物理机网络转发到目的云主机。
====

* VXLAN网络
[quote]
====
物理服务器之间先建立VXLAN隧道，根据目的云主机所在的物理机，通过VXLAN隧道转发到目的云主机。
====

* 硬件VXLAN网络
[quote]
====
这个类型对应硬件SDN网络overlay方案。物理服务器给云主机的流量打上VLAN标签，SDN交换机根据VLAN ID映射到一个VXLAN网络。
和VXLAN类型的区别在于:

** VXLAN网络的VXLAN的封装，解封装由物理服务器完成，而且VXLAN VTEP是物理机的业务接口地址地址，
** 硬件VXLAN网络的VXLAN的封装，解封装由SDN交换机完成，而且VXLAN VTEP是SDN交换机的地址。

目前支持的SDN控制器有 `H3C VCFC Controller`， SDN厂商也可根据SDN框架自行开发插件适配ZStack平台.
====

== 三层网络
云主机通过二层网络连通以后，云主机还需要地址管理，地址分配，安全组，DNS, userdata等更多高级功能。三层网络首先定义了云主机使用的IP地址段，
然后三层网络还定义云主机是否需要使用更多高级功能. 根据使用场景，三层网络包含以下类型：

* 公有网络
[quote]
====
通过公有网络，云主机可以和物理网络互通，因此，公有网络IP地址段是物理网络某个地址段的一部分。
公有网络的物理拓扑结果如下：

image::publicNetwork.xml.svg[]
====

* 扁平网络
[quote]
====
扁平网络可以定义一个只有云平台使用的IP地址段，不必考虑和物理机网络互通。

** 如果使用了IPv6地址段，必须在物理路由器上配置扁平网络的网关。因为只有网关才能发送了Router Advertisement通告，云主机才能获取到路由前缀的长度.

扁平网络的物理拓扑结果如下：

image::flatNetwork.xml.svg[]
====

* VPC网络
[quote]
====
和扁平网络一样，VPC网络也可以定义一个只有云平台才使用IP地址段，但是VPC网络的网关是由VPC路由器提供的，IPv6的Router Advertisement通告由VPC路由器
发送。

VPC网络网络的物理拓扑结果如下：

image::vpcNetwork.xml.svg[]
====

== VPC路由器

VPC路由器为VPC网络提供网关的功能，同时它还提供SNAT, 弹性IP, 端口转发，IPSec, 负载均衡，VipQos, 路由表，OSPF, 防火墙，组播转发，Netflow，
源进源出等网络功能

== VPC高可用组

VPC路由器作为网络业务的一个核心节点，为了避免单点故障，VPC高可用组创建两台完全相同配置的两台VPC，通过Keepalived, 选举其中一台为Master路由器。
如果Master故障，Backup路由器能迅速切换到为Master路由器，快速恢复网络流量。

