//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 11:28:57 PM PDT 
//


package org.zstack.configuration.testlink.schema;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="req_spec">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="node_order" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="requirement">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="docid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="node_order" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/sequence>
 *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="doc_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reqSpec"
})
@XmlRootElement(name = "requirement-specification")
public class RequirementSpecification {

    @XmlElement(name = "req_spec", required = true)
    protected RequirementSpecification.ReqSpec reqSpec;

    /**
     * Gets the value of the reqSpec property.
     * 
     * @return
     *     possible object is
     *     {@link RequirementSpecification.ReqSpec }
     *     
     */
    public RequirementSpecification.ReqSpec getReqSpec() {
        return reqSpec;
    }

    /**
     * Sets the value of the reqSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequirementSpecification.ReqSpec }
     *     
     */
    public void setReqSpec(RequirementSpecification.ReqSpec value) {
        this.reqSpec = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="node_order" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="requirement">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="docid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="node_order" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/sequence>
     *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="doc_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scope",
        "nodeOrder",
        "requirement"
    })
    public static class ReqSpec {

        @XmlElement(required = true)
        protected String scope;
        @XmlElement(name = "node_order", required = true)
        protected String nodeOrder;
        protected List<RequirementSpecification.ReqSpec.Requirement> requirement;
        @XmlAttribute
        protected String title;
        @XmlAttribute(name = "doc_id")
        protected String docId;

        /**
         * Gets the value of the scope property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScope() {
            return scope;
        }

        /**
         * Sets the value of the scope property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScope(String value) {
            this.scope = value;
        }

        /**
         * Gets the value of the nodeOrder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNodeOrder() {
            return nodeOrder;
        }

        /**
         * Sets the value of the nodeOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNodeOrder(String value) {
            this.nodeOrder = value;
        }

        /**
         * Gets the value of the requirement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requirement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequirement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RequirementSpecification.ReqSpec.Requirement }
         * 
         * 
         */
        public List<RequirementSpecification.ReqSpec.Requirement> getRequirement() {
            if (requirement == null) {
                requirement = new ArrayList<RequirementSpecification.ReqSpec.Requirement>();
            }
            return this.requirement;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the docId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocId() {
            return docId;
        }

        /**
         * Sets the value of the docId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocId(String value) {
            this.docId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="docid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="node_order" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "docid",
            "title",
            "nodeOrder",
            "description"
        })
        public static class Requirement {

            @XmlElement(required = true)
            protected String docid;
            @XmlElement(required = true)
            protected String title;
            @XmlElement(name = "node_order", required = true)
            protected String nodeOrder;
            @XmlElement(required = true)
            protected String description;

            /**
             * Gets the value of the docid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDocid() {
                return docid;
            }

            /**
             * Sets the value of the docid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDocid(String value) {
                this.docid = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the nodeOrder property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNodeOrder() {
                return nodeOrder;
            }

            /**
             * Sets the value of the nodeOrder property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNodeOrder(String value) {
                this.nodeOrder = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

        }

    }

}
