//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 11:28:57 PM PDT 
//


package org.zstack.configuration.testlink.schema;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="req">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="prerequisite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="goal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="details" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                       &lt;element name="subResource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;/sequence>
 *                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                       &lt;element name="relationalResource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;/sequence>
 *                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                       &lt;element name="api">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="requestClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                 &lt;element name="responseClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                     &lt;element name="other" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scope",
    "title",
    "documentId",
    "req"
})
@XmlRootElement(name = "requirementCategory")
public class RequirementCategory {

    @XmlElement(required = true)
    protected String scope;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String documentId;
    protected List<RequirementCategory.Req> req;

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the documentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentId(String value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the req property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the req property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequirementCategory.Req }
     * 
     * 
     */
    public List<RequirementCategory.Req> getReq() {
        if (req == null) {
            req = new ArrayList<RequirementCategory.Req>();
        }
        return this.req;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="prerequisite" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="goal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="details" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="subResource" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;/sequence>
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="relationalResource" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;/sequence>
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="api">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="requestClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="responseClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *         &lt;element name="other" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prerequisite",
        "goal",
        "details",
        "title",
        "subResource",
        "relationalResource",
        "api",
        "other"
    })
    public static class Req {

        @XmlElement(required = true)
        protected String prerequisite;
        @XmlElement(required = true)
        protected String goal;
        @XmlElement(required = true)
        protected String details;
        @XmlElement(required = true)
        protected String title;
        protected List<String> subResource;
        protected List<String> relationalResource;
        protected List<RequirementCategory.Req.Api> api;
        @XmlElement(required = true)
        protected String other;

        /**
         * Gets the value of the prerequisite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrerequisite() {
            return prerequisite;
        }

        /**
         * Sets the value of the prerequisite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrerequisite(String value) {
            this.prerequisite = value;
        }

        /**
         * Gets the value of the goal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGoal() {
            return goal;
        }

        /**
         * Sets the value of the goal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGoal(String value) {
            this.goal = value;
        }

        /**
         * Gets the value of the details property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDetails() {
            return details;
        }

        /**
         * Sets the value of the details property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDetails(String value) {
            this.details = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the subResource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subResource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubResource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSubResource() {
            if (subResource == null) {
                subResource = new ArrayList<String>();
            }
            return this.subResource;
        }

        /**
         * Gets the value of the relationalResource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relationalResource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelationalResource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRelationalResource() {
            if (relationalResource == null) {
                relationalResource = new ArrayList<String>();
            }
            return this.relationalResource;
        }

        /**
         * Gets the value of the api property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the api property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApi().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RequirementCategory.Req.Api }
         * 
         * 
         */
        public List<RequirementCategory.Req.Api> getApi() {
            if (api == null) {
                api = new ArrayList<RequirementCategory.Req.Api>();
            }
            return this.api;
        }

        /**
         * Gets the value of the other property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOther() {
            return other;
        }

        /**
         * Sets the value of the other property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOther(String value) {
            this.other = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="requestClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="responseClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "requestClass",
            "responseClass"
        })
        public static class Api {

            @XmlElement(required = true)
            protected String requestClass;
            @XmlElement(required = true)
            protected String responseClass;

            /**
             * Gets the value of the requestClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequestClass() {
                return requestClass;
            }

            /**
             * Sets the value of the requestClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequestClass(String value) {
                this.requestClass = value;
            }

            /**
             * Gets the value of the responseClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResponseClass() {
                return responseClass;
            }

            /**
             * Sets the value of the responseClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResponseClass(String value) {
                this.responseClass = value;
            }

        }

    }

}
