package org.zstack.test.integration.core

import org.zstack.testlib.SubCase

/**
 * Created by lining on 2017/4/10.
 */
class MustPassCase extends SubCase {

    @Override
    void clean() {
    }

    @Override
    void setup() {
    }

    @Override
    void environment() {
    }

    @Override
    void test() {
        // context : Verify the validity of the test results, and when the case is passed, expect the test results generated by the test framework
        // must pass
        assert true
    }
}
