package org.zstack.kvm.memory;

public enum MemoryErrors {
    MEMORY_REQUEST_TOO_LARGE("MEMORY_REQUEST_TOO_LARGE", 11000),
    MEMORY_BACKEND_PREPARATION_INVALID("MEMORY_BACKEND_PREPARATION_INVALID", 11001),
    MEMORY_CONTROLLER_CONFLICT("MEMORY_CONTROLLER_CONFLICT", 11002),
    MEMORY_DRAIN_REQUIRED("MEMORY_DRAIN_REQUIRED", 11003),
    MEMORY_MIGRATION_HOLD_PENDING("MEMORY_MIGRATION_HOLD_PENDING", 11004),
    MEMORY_PARTICIPATION_UNCONFIRMED("MEMORY_PARTICIPATION_UNCONFIRMED", 11005),
    MEMORY_RESULT_UNKNOWN("MEMORY_RESULT_UNKNOWN", 11006),
    MEMORY_INVALID_PAGE_SIZE("MEMORY_INVALID_PAGE_SIZE", 11007),
    MEMORY_INVALID_RUNTIME_SETTING("MEMORY_INVALID_RUNTIME_SETTING", 11008),
    MEMORY_BACKEND_QUERY_UNAVAILABLE("MEMORY_BACKEND_QUERY_UNAVAILABLE", 11009),
    MEMORY_HOST_NOT_CONNECTED("MEMORY_HOST_NOT_CONNECTED", 11010),
    MEMORY_INSTANCE_CHANGED("MEMORY_INSTANCE_CHANGED", 11011),
    MEMORY_INVALID_REQUEST("MEMORY_INVALID_REQUEST", 11012),
    MEMORY_LICENSE_UNAVAILABLE("MEMORY_LICENSE_UNAVAILABLE", 11013),
    MEMORY_OBSERVATION_UNAVAILABLE("MEMORY_OBSERVATION_UNAVAILABLE", 11014),
    MEMORY_OPERATION_QUERY_UNAVAILABLE("MEMORY_OPERATION_QUERY_UNAVAILABLE", 11015),
    MEMORY_PERMISSION_DENIED("MEMORY_PERMISSION_DENIED", 11016),
    MEMORY_CAPABILITY_PRECHECK("MEMORY_CAPABILITY_PRECHECK", 11017),
    MEMORY_CONTROL_OPERATION_FENCED("MEMORY_CONTROL_OPERATION_FENCED", 11018),
    MEMORY_CONTROL_OPERATION_REQUIRED("MEMORY_CONTROL_OPERATION_REQUIRED", 11019),
    MEMORY_CONTROL_PAUSED_RESUME_REQUIRED("MEMORY_CONTROL_PAUSED_RESUME_REQUIRED", 11020),
    MEMORY_HOST_BUSY("MEMORY_HOST_BUSY", 11021),
    MEMORY_IDEMPOTENCY_CONFLICT("MEMORY_IDEMPOTENCY_CONFLICT", 11022),
    MEMORY_INSTANCE_REQUIRED("MEMORY_INSTANCE_REQUIRED", 11023),
    MEMORY_INVALID_ACTION("MEMORY_INVALID_ACTION", 11024),
    MEMORY_INVALID_PAGE("MEMORY_INVALID_PAGE", 11025),
    MEMORY_INVALID_POLICY("MEMORY_INVALID_POLICY", 11026),
    MEMORY_INVALID_SCOPE("MEMORY_INVALID_SCOPE", 11027),
    MEMORY_NOT_CANCELLABLE("MEMORY_NOT_CANCELLABLE", 11028),
    MEMORY_NOT_READY("MEMORY_NOT_READY", 11029),
    MEMORY_POLICY_PRESENT("MEMORY_POLICY_PRESENT", 11030),
    MEMORY_QUERY_SNAPSHOT_CHANGED("MEMORY_QUERY_SNAPSHOT_CHANGED", 11031),
    MEMORY_RESUME_NOT_PAUSED("MEMORY_RESUME_NOT_PAUSED", 11032),
    MEMORY_RESUME_STATE_UNKNOWN("MEMORY_RESUME_STATE_UNKNOWN", 11033),
    MEMORY_REVISION_CONFLICT("MEMORY_REVISION_CONFLICT", 11034),
    MEMORY_TARGET_SNAPSHOT_CONFLICT("MEMORY_TARGET_SNAPSHOT_CONFLICT", 11035),
    MEMORY_TARGET_SNAPSHOT_INCOMPLETE("MEMORY_TARGET_SNAPSHOT_INCOMPLETE", 11036),
    MEMORY_UNCERTAIN_RECOVERY_FENCED("MEMORY_UNCERTAIN_RECOVERY_FENCED", 11037),
    MEMORY_INVALID_TARGETS("MEMORY_INVALID_TARGETS", 11038),
    MEMORY_TARGET_SNAPSHOT_DIGEST_MISMATCH("MEMORY_TARGET_SNAPSHOT_DIGEST_MISMATCH", 11039),
    MEMORY_UNCERTAIN_RECOVERY_INVALID("MEMORY_UNCERTAIN_RECOVERY_INVALID", 11040),
    MEMORY_ZRAM_POOL_PREPARATION_INVALID("MEMORY_ZRAM_POOL_PREPARATION_INVALID", 11041),
    MEMORY_TASK_NOT_ROOT("MEMORY_TASK_NOT_ROOT", 11042),
    MEMORY_TASK_REFERENCED("MEMORY_TASK_REFERENCED", 11043),
    MEMORY_REQUEST_RESULT_PURGED("MEMORY_REQUEST_RESULT_PURGED", 11044),
    MEMORY_SERVICE_NOT_STOPPED("MEMORY_SERVICE_NOT_STOPPED", 11045),
    UNKNOWN("MEMORY_UNKNOWN_ERROR", 11999);

    private static final String PREFIX = "MEMORY_ERROR";
    private final String businessCode;
    private final int id;
    private final String metadataCode;

    MemoryErrors(String businessCode, int id) {
        this.businessCode = businessCode;
        this.id = id;
        this.metadataCode = String.format("%s.%d", PREFIX, id);
    }

    public String getBusinessCode() {
        return businessCode;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return metadataCode;
    }

    public static MemoryErrors fromBusinessCode(String code) {
        for (MemoryErrors error : values()) {
            if (error.businessCode.equals(code)) {
                return error;
            }
        }
        return UNKNOWN;
    }
}
