//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.23 at 02:21:36 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://zstack.org/schema/zstack", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@XmlJavaTypeAdapter(value=StringTrimAdapter.class,type=String.class)
package org.zstack.portal.apimediator.schema;

import org.zstack.utils.jaxb.StringTrimAdapter;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;